version: '4.34.3'
services:
  postgres:
    container_name: theAgesPostgresDB
    image: postgres:latest
    environment:
      POSTGRES_DB: "TheAgesDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "kjkjrgjwe2354fs"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postgres-data:
